### ISSUE TITLE
Unsupported Attribute when writing attributes to Sonoff TRVZB

### ISSUE THREAD

**Issue by photomoose** [Koenkk/zigbee-herdsman-converters#7436]
#7432 appears to have stopped the ability to write attributes to the Sonoff TRV (e.g. child lock, open window detection). The TRVs are responding with 'Unsupported Attribute':

```
Publish 'get' 'open_window' to 'Kitchen' failed: 'Error: ZCL command 0x3c2ef5fffebd4de2/1 sonoffTrvzbCluster.read(["openWindow"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4742,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

It looks like the addition of the Manufacturer Code in the ZCL Frame is the culprit; if I remove [this line](https://github.com/Koenkk/zigbee-herdsman-converters/blob/1b5bad8a1bf795a0e15e82fef6d4f536a56e3b9e/src/devices/sonoff.ts#L918), then it works as expected.

I have attached traces of packets sent from Z2M and packets sent from eWeLink/ZB-Bridge. You can clearly see that eWeLink does not include the Manufacturer Code.

[Traces.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/15093467/Traces.zip)

**Comment by fir3drag0n** [comment]
I can confirm the problem: https://github.com/Koenkk/zigbee-herdsman-converters/pull/7130

**Comment by einfachuli** [comment]
Exactly the same Problem here.

**Comment by photomoose** [comment]
From looking at previous commits/conversations, I assume the manufacturer code was included so that it is echoed in the response from the device, allowing Z2M to differentiate between different devices using the same cluster ID - so I'm not sure that simply removing the manufacturer code from the Sonoff cluster definition is the correct thing to do here. @Koenkk can you confirm?

**Comment by Koenkk** [comment]
@photomoose I pushed a fix, can you check if this is fixed now?

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by photomoose** [comment]
@Koenkk sure no problem, I've been running it locally (npm run start) so will check as soon as I finish my dinner! 😀

**Comment by hubi73** [comment]
I have tested the dev branch with zigbee-herdsman (0.43.1) but still get this error:

[2024-04-25 22:05:17] error:    z2m: Publish 'get' 'valve_closing_degree' to 'TRV-Bad' failed: 'Error: ZCL command 0x38398ffffe020ee5/1 sonoffTrvzbCluster.read(["valveClosingDegree"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4742,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
[2024-04-25 22:05:17] error:    z2m: Exception while calling fromZigbee converter: Value is not a number, got undefined (undefined)}

**Comment by photomoose** [comment]
@Koenkk looks like the changes in the `customSonoffTrvzb` cluster have fixed the issue. Thanks for the fix! Also checked the valve closing/opening degree issue raised by @hubi73 but this appears to be working fine for me, as shown in the attached traces.

[Fixed.pcapng.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/15121988/Fixed.pcapng.zip)

**Comment by fir3drag0n** [comment]
I still get errors with latest dev:

` 2024-04-29 08:16:51Configuring 'TRV-Küche'
Error 2024-04-29 08:16:51Publish 'set' 'valve_opening_degree' to 'TRV-Küche' failed: 'Error: ZCL command 0x0cae5ffffeb0dc77/1 sonoffTrvzbCluster.write({"valveOpeningDegree":63}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4742,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Error 2024-04-29 08:16:53Exception while calling fromZigbee converter: Value is not a number, got undefined (undefined)}
Error 2024-04-29 08:16:53Failed to configure 'TRV-Küche', attempt 1 (Error: ZCL command 0x0cae5ffffeb0dc77/1 sonoffTrvzbCluster.read([0,24576,24578,24579,24580,24581,24582,24583], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4742,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:314:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:769:26) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:400:29) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/sonoff.ts:911:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:21) at Configure.configure (/app/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
Info 2024-04-29 08:17:04Configuring 'TRV-Küche'
Error 2024-04-29 08:17:04Publish 'set' 'valve_opening_degree' to 'TRV-Küche' failed: 'Error: ZCL command 0x0cae5ffffeb0dc77/1 sonoffTrvzbCluster.write({"valveOpeningDegree":36}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4742,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Error 2024-04-29 08:17:06Exception while calling fromZigbee converter: Value is not a number, got undefined (undefined)}`
