### ISSUE TITLE
Girier JR-ZPM01

### ISSUE THREAD

**Issue by novittukyll** [Koenkk/zigbee-herdsman-converters#9612]
I created PR as this plug was detected as "Tuya TS011F_plug_3", but correct should be "Tuya TS011F_plug_1". After the latest update this plug still shows up as "Tuya TS011F_plug_3". Do we need to change anything else in the tuya.ts?

https://github.com/Koenkk/zigbee-herdsman-converters/pull/9456

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of this device?

**Comment by novittukyll** [comment]
`{"id":29,"type":"Router","ieeeAddr":"0xa4c138913800a1fc","nwkAddr":8821,"manufId":4107,"manufName":"_TZ3000_ww6drja5","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,10,57344,1794,2820,4096,6280],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_ww6drja5","powerSource":1,"zclVersion":3,"appVersion":112,"stackVersion":2,"hwVersion":0,"swBuildId":"1.0.5\u0000"}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":111,"rmsCurrent":0,"activePower":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":708}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"tuyaBacklightMode":0,"moesStartUpOnOff":0,"onTime":0,"offWaitTime":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":112,"stackVersion":2,"hwVersion":0,"swBuildId":"1.0.5\u0000","zclVersion":3,"interviewCompleted":true,"interviewState":"SUCCESSFUL","meta":{"configured":332242049},"lastSeen":1752296529289}`

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by novittukyll** [comment]
Power monitoring works fine with this plug. There is no need to use polling.

Currently it is detected as this: https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html
Thats why I created PR to be detected as Plug 1(https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html), but that didn't work and it still shows up as plug 3.

**Comment by Koenkk** [comment]
sorry, read it wrong, fixed now!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.
